import { esc, badge } from './ui-kit.js';

const itemButton = (item,type) => `<button class="item-title" data-${type==='task'?'task':'requirement'}="${esc(item.id)}">${esc(item.title)}</button>`;
export function renderPersonalWork(result,{projectName,nameOf}) {
  const section=([title,items,type])=>`<section class="panel"><div class="panel-heading"><h2>${title} <span class="count-label">${items.length} 项</span></h2></div>${items.length?`<div class="work-list">${items.map(item=>`<article class="work-item"><div>${itemButton(item,type)}<p>${esc(projectName(item.projectId))} · ${esc(nameOf(item.ownerId||item.assigneeId))} · ${esc(item.dueDate||item.planEnd||'未排期')}</p></div>${badge(item.status)}</article>`).join('')}</div>`:'<div class="work-empty">当前没有需要处理的事项。</div>'}</section>`;
  // Lead developers see confirmed requirements awaiting a split above their own work.
  const splits=result.personal.isLead?section(['待我拆分的需求',result.personal.splits||[],'requirement']):'';
  return `${splits}<div class="work-columns">${[['我的任务',result.personal.tasks,'task'],['我负责或协作的需求',result.personal.requirements,'requirement'],['待我验收',result.personal.reviews,'task']].map(section).join('')}</div>`;
}
export function renderReminders(result,{projectName}) {
  return `<section class="panel"><div class="panel-heading"><h2>交付与验收提醒 <span class="count-label">${result.unread} 条未读</span></h2><div class="page-actions"><button class="btn btn-secondary btn-small" data-action="read-all-notifications"${result.unread?'':' disabled'}>全部标为已读</button></div></div><div class="panel-intro"><p class="field-help">提醒会在打开页面或点击刷新时更新。包括逾期、未来三天到期、前置任务阻塞、待验收、待拆分需求和开发补充的任务；已读不会解除风险。</p></div>${result.reminders.length?`<div class="work-list">${result.reminders.map(item=>`<article class="work-item${item.read?' is-read':''}"><span class="notice-dot${item.read?' is-read':''}" aria-label="${item.read?'已读':'未读'}"></span><div>${itemButton({id:item.entityId,title:item.title},item.entityType)}<p>${esc(projectName(item.projectId))} · ${esc(item.message)}</p></div>${!item.read?`<button class="text-button" data-read-notification="${esc(item.id)}">标为已读</button>`:'<span class="muted small">已读</span>'}</article>`).join('')}</div>`:'<div class="work-empty">当前没有交付或验收提醒。</div>'}</section>`;
}
export function renderReports(result) {
  const max=Math.max(1,...result.trend.flatMap(item=>[item.createdRequirements,item.completedTasks]));
  const rate=item=>item.overdueRate===null?'<span class="muted">暂无已排期任务</span>':`<span class="rate-cell"><span class="rate-track"><i style="width:${Math.min(100,item.overdueRate)}%"></i></span><strong class="${item.overdueRate>0?'overdue-text':''}">${item.overdueRate}%</strong></span>`;
  return `<section class="panel"><div class="panel-heading"><h2>跨项目交付风险</h2><span class="muted small">截至 ${esc(result.date)}</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>项目</th><th>未完成</th><th>已逾期</th><th>未排期</th><th>逾期率</th></tr></thead><tbody>${result.health.map(item=>`<tr><td><a class="item-title" href="#/p/${encodeURIComponent(item.projectId)}/timeline">${esc(item.name)}</a></td><td class="num-cell">${item.pending}</td><td class="num-cell${item.overdue?' overdue-text':''}">${item.overdue}</td><td class="num-cell">${item.unscheduled}</td><td>${rate(item)}</td></tr>`).join('')}</tbody></table></div><div class="panel-note">逾期率 = 逾期未完成任务 ÷ 已设置截止日期的未完成任务；已终止和归档任务不参与。未排期单独展示，避免被当作正常交付。</div></section><section class="panel"><div class="panel-heading"><h2>最近八周变化</h2><span class="muted small">本周截至今天</span></div><div class="panel-pad"><p class="field-help">统计当前可见、未归档项目中的有效需求与任务。缺少完成日期的 ${result.undatedCompleted} 个已完成任务不计入趋势；不补造历史日期。</p><div class="trend-legend"><span>新增需求</span><span>完成任务</span></div><div class="trend-chart" role="img" aria-label="最近八周新增需求与完成任务，完整数值见下表">${result.trend.map(week=>`<div class="trend-week"><div class="trend-bars"><i style="height:${week.createdRequirements/max*100}%" title="新增需求 ${week.createdRequirements}"></i><i style="height:${week.completedTasks/max*100}%" title="完成任务 ${week.completedTasks}"></i></div><span>${week.start.slice(5)}</span></div>`).join('')}</div><details class="change-details"><summary>查看逐周数值</summary><div class="table-wrap"><table class="change-table"><thead><tr><th>周开始</th><th>新增需求</th><th>完成任务</th></tr></thead><tbody>${result.trend.map(week=>`<tr><th scope="row">${week.start}</th><td>${week.createdRequirements}</td><td>${week.completedTasks}</td></tr>`).join('')}</tbody></table></div></details><div class="cycle-stat"><span>从创建到完成平均用时</span><strong>${result.cycle.averageDays===null?'—':result.cycle.averageDays+'<small> 天</small>'}</strong><p class="field-help">${result.cycle.averageDays===null?'暂无可计算记录；':''}样本 ${result.cycle.count} 个，取本区间完成且创建日期有效的任务。</p></div></div></section>`;
}
